@HostAddress = https://ticket-booking-api-lgc6.onrender.com

### Dapatkan Semua Konser
GET {{HostAddress}}/api/concerts
Accept: application/json

### Bikin Konser 1: Coldplay
POST {{HostAddress}}/api/concerts
Content-Type: application/json

{
  "name": "Coldplay Live in Jakarta",
  "date": "2026-11-15T19:00:00Z",
  "totalTickets": 50000
}

### Bikin Konser 2: Taylor Swift
POST {{HostAddress}}/api/concerts
Content-Type: application/json

{
  "name": "Taylor Swift - Eras Tour SG",
  "date": "2027-03-02T18:00:00Z",
  "totalTickets": 60000
}

### Bikin Konser 3: Sheila on 7
POST {{HostAddress}}/api/concerts
Content-Type: application/json

{
  "name": "Sheila on 7 - Tunggu Aku di Awan",
  "date": "2026-12-01T15:00:00Z",
  "totalTickets": 5000
}

### Beli Tiket
POST {{HostAddress}}/api/bookings
Content-Type: application/json

{
  "concertId": "b193dc05-e1bf-4eb9-b5f4-ad0a02fe40b9",
  "customerName": "Achmad Soewardi"
}
