@TikectingBookingApi_HostAddress = http://localhost:5098

GET {{TikectingBookingApi_HostAddress}}/api/concerts
Accept: application/json

### Membuat Konser Baru
POST http://localhost:5098/api/concerts
Content-Type: application/json

{
  "name": "The Panturas", 
  "date": "2026-11-15T19:00:00Z",
  "totalTickets": 10
}

### Booking Tiket
POST http://localhost:5098/api/bookings
Content-Type: application/json

{
  "concertId": "5a016cbb-09ac-4f74-b68e-6591c50507be",
  "customerName": "Ardi"
}


### -------------------------------------------------
### TEST CASE FASE 4 (CRUD Lanjutan)
### -------------------------------------------------

### 1. Dapatkan 1 Konser Spesifik (GetConcertById)
# (Ganti ID dengan ID Konser yang valid dari hasil GET /api/concerts)
@concert_id = 20a0e653-6223-4250-be8b-dd3c7cf73b0f
GET http://localhost:5098/api/concerts/{{concert_id}}
Accept: application/json

### 2. Update Konser (Ganti Nama / Total Tiket)
PUT http://localhost:5098/api/concerts/{{concert_id}}
Content-Type: application/json

{
  "id": "{{concert_id}}",
  "name": "Apa Kek Yang Penting Ada", 
  "date": "2026-12-20T20:00:00Z",
  "totalTickets": 50
}

### 3. Lihat Daftar Booking untuk Konser Tersebut
GET http://localhost:5098/api/bookings?concertId={{concert_id}}
Accept: application/json

### 4. Hapus Konser (Akan gagal jika masih ada tiket ter-booking)
DELETE http://localhost:5098/api/concerts/{{concert_id}}
